services:
  ls-server: 
    image: registry.digitalocean.com/gtcr/ls-server:latest
    build: .
    ports:
      - 3333:3333
    depends_on:
      - mongo
    
  nginx-rtmp:
    image: registry.digitalocean.com/gtcr/nginx-rtmp:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000
      - 1935:1935
    depends_on:
      - ls-server

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data: