services:
  ls-server: 
    env_file:
      - .env
    image: registry.digitalocean.com/gtcr/ls-server:latest
    ports:
      - 3333:3333
    depends_on:
      - mongo
    
  nginx-rtmp:
    image: registry.digitalocean.com/gtcr/nginx-rtmp:latest
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      - ./nginx/api.lsstack.xyz:/etc/nginx/sites-available/api.lsstack.xyz
      - ./nginx/rtmp.lsstack.xyz:/etc/nginx/sites-available/rtmp.lsstack.xyz
      - ./nginx/api.lsstack.xyz:/etc/nginx/sites-enabled/api.lsstack.xyz
      - ./nginx/rtmp.lsstack.xyz:/etc/nginx/sites-enabled/rtmp.lsstack.xyz
    depends_on:
      - ls-server

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data: