services:
  ls-server: 
    image: registry.digitalocean.com/gtcr/ls-server:latest
    env_file:
      - .env
    container_name: ls-server
    build: .
    ports:
      - 3333:3333
    depends_on:
      - mongo
    
  nginx-rtmp:
    image: registry.digitalocean.com/gtcr/nginx-rtmp:latest
    container_name: nginx
    build:
      context: ./nginx
      args:
        ENABLED_MODULES: rtmp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    depends_on:
      - ls-server

  mongo:
    container_name: database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data: